USE [TM_PDWAC_DB]
GO

DROP PROCEDURE IF EXISTS [SEGURIDAD].[TM_PDWAC_SP_DOCUMENTOS_PERFIL]
GO

-----------------------------------------------------------------------------
-- PROCEDURE   :   [SEGURIDAD].[TM_PDWAC_SP_DOCUMENTOS_PERFIL]
-- DESCRIPTION :   DEVUELVE LOS DOCUMENTOS QUE PUEDE APROBAR
-- DATE        :   01/08/2021
-- AUTHOR      :   RAFAEL RAYMUNDES LÓPEZ
----------------------------------------------------------------------------- 
CREATE PROC [SEGURIDAD].[TM_PDWAC_SP_DOCUMENTOS_PERFIL](
	@ID_PERFIL	INT
)
AS
	SELECT COD_DOCUMENTO
	  FROM TM_PDWAC_TB_PERFIL_DOCUMENTO
	 WHERE ID_PERFIL = @ID_PERFIL
GO


