USE [TM_PDWAC_DB]
GO

DROP PROCEDURE IF EXISTS [dbo].[TM_PDWAC_SP_SOLICITUD_LEER]
GO

-----------------------------------------------------------------------------
-- PROCEDURE   :   [dbo].[TM_PDWAC_SP_SOLICITUD_LEER]
-- DESCRIPTION :   DEVUELVE TODAS LAS SOLICITUDES DE REGISTRO AL SISTEMA
-- DATE        :   01/08/2021
-- AUTHOR      :   RAFAEL RAYMUNDES LÓPEZ
----------------------------------------------------------------------------- 
CREATE PROC [dbo].[TM_PDWAC_SP_SOLICITUD_LEER]      
 @SOLI_CODIGO VARCHAR(50),    
 @SOLI_RUCDNI VARCHAR(15),    
 @SOLI_ESTADO VARCHAR(2)    
AS      
        SELECT SOLI_CODIGO,       
               SOLI_FECHA_REGISTRO,       
               UPPER(IIF(SOLI_TIPODOCUMENTO='RUC', SOLI_RAZON_SOCIAL, SOLI_RELEGAL_NOMBRE+' '+SOLI_RLEGAL_APELLIDO_PATERNO+' '+SOLI_RLEGAL_APELLIDO_MATERNO)) SOLI_RAZON_SOCIAL,        
               SOLI_ESTADO SOLI_ESTADO_CODIGO,      
               UPPER(PR.PRMT_NOMBRE) SOLI_ESTADO_NOMBRE,
               SOLI_ACUERDO_SEGUR_CADENA_SUMINI
         FROM TM_PDWAC_TB_SOLICITUDACCESO SO      
   INNER JOIN TM_PDWAC_TB_PARAMETRO PR      
           ON SO.SOLI_ESTADO = PR.PRMT_VALOR      
          AND PR.PRMT_IDPADRE = 34    
        WHERE (@SOLI_CODIGO = '0' OR SO.SOLI_CODIGO = @SOLI_CODIGO)    
            AND (@SOLI_RUCDNI = '0' OR SO.SOLI_NUMERO_DOCUMENTO = @SOLI_RUCDNI)    
            AND (@SOLI_ESTADO = '0' OR RTRIM(LTRIM(SO.SOLI_ESTADO)) = @SOLI_ESTADO)    
     ORDER BY SO.SOLI_FECHA_REGISTRO DESC
GO


