CREATE TABLE [dbo].[TM_PDWAC_TB_PERFIL_DOCUMENTO](
	[PERFDOC_ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERFIL] [varchar](4) NULL,
	[COD_DOCUMENTO] [varchar](4) NULL,
PRIMARY KEY CLUSTERED 
(
	[PERFDOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
