//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_TM_PWSoap")]
    public interface WebService_TM_PWSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ListarEmbarques", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ListarEmbarquesResponse TM_WS_ListarEmbarques(ServiceReference1.TM_WS_ListarEmbarquesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ListarEmbarques", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ListarEmbarquesResponse> TM_WS_ListarEmbarquesAsync(ServiceReference1.TM_WS_ListarEmbarquesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerInformacionEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerInformacionEmbarqueResponse TM_WS_ObtenerInformacionEmbarque(ServiceReference1.TM_WS_ObtenerInformacionEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerInformacionEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerInformacionEmbarqueResponse> TM_WS_ObtenerInformacionEmbarqueAsync(ServiceReference1.TM_WS_ObtenerInformacionEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerTrackingEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerTrackingEmbarqueResponse TM_WS_ObtenerTrackingEmbarque(ServiceReference1.TM_WS_ObtenerTrackingEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerTrackingEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerTrackingEmbarqueResponse> TM_WS_ObtenerTrackingEmbarqueAsync(ServiceReference1.TM_WS_ObtenerTrackingEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCobrosEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerCobrosEmbarqueResponse TM_WS_ObtenerCobrosEmbarque(ServiceReference1.TM_WS_ObtenerCobrosEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCobrosEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCobrosEmbarqueResponse> TM_WS_ObtenerCobrosEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCobrosEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_RegistrarDocumentoResponse TM_WS_RegistrarDocumento(ServiceReference1.TM_WS_RegistrarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarDocumentoResponse> TM_WS_RegistrarDocumentoAsync(ServiceReference1.TM_WS_RegistrarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarDocumentoResponse TM_WS_ActualizarDocumento(ServiceReference1.TM_WS_ActualizarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarDocumentoResponse> TM_WS_ActualizarDocumentoAsync(ServiceReference1.TM_WS_ActualizarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarAgenteAduanasEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueResponse TM_WS_ActualizarAgenteAduanasEmbarque(ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarAgenteAduanasEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueResponse> TM_WS_ActualizarAgenteAduanasEmbarqueAsync(ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCobrosPendientesEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueResponse TM_WS_ObtenerCobrosPendientesEmbarque(ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCobrosPendientesEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueResponse> TM_WS_ObtenerCobrosPendientesEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerEntidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerEntidadesResponse TM_WS_ObtenerEntidades(ServiceReference1.TM_WS_ObtenerEntidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerEntidades", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerEntidadesResponse> TM_WS_ObtenerEntidadesAsync(ServiceReference1.TM_WS_ObtenerEntidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerDesglosesEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueResponse TM_WS_ObtenerDesglosesEmbarque(ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerDesglosesEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueResponse> TM_WS_ObtenerDesglosesEmbarqueAsync(ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarAutorizacionEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueResponse TM_WS_ActualizarAutorizacionEmbarque(ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarAutorizacionEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueResponse> TM_WS_ActualizarAutorizacionEmbarqueAsync(ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCreditoCobroEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueResponse TM_WS_ObtenerCreditoCobroEmbarque(ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerCreditoCobroEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueResponse> TM_WS_ObtenerCreditoCobroEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudFacturacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_RegistrarSolicitudFacturacionResponse TM_WS_RegistrarSolicitudFacturacion(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudFacturacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudFacturacionResponse> TM_WS_RegistrarSolicitudFacturacionAsync(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudFacturacionDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleResponse TM_WS_RegistrarSolicitudFacturacionDetalle(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudFacturacionDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleResponse> TM_WS_RegistrarSolicitudFacturacionDetalleAsync(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerEstadoSolicitudFacturacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionResponse TM_WS_ObtenerEstadoSolicitudFacturacion(ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ObtenerEstadoSolicitudFacturacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionResponse> TM_WS_ObtenerEstadoSolicitudFacturacionAsync(ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarPagosTercero", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarPagosTerceroResponse TM_WS_ActualizarPagosTercero(ServiceReference1.TM_WS_ActualizarPagosTerceroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarPagosTercero", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarPagosTerceroResponse> TM_WS_ActualizarPagosTerceroAsync(ServiceReference1.TM_WS_ActualizarPagosTerceroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudDireccionamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoResponse TM_WS_RegistrarSolicitudDireccionamiento(ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarSolicitudDireccionamiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoResponse> TM_WS_RegistrarSolicitudDireccionamientoAsync(ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarEstadoSolicitudDireccionamiento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse TM_WS_ActualizarEstadoSolicitudDireccionamiento(ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarEstadoSolicitudDireccionamiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse> TM_WS_ActualizarEstadoSolicitudDireccionamientoAsync(ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarDireccionamientoPermanente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteResponse TM_WS_RegistrarDireccionamientoPermanente(ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_RegistrarDireccionamientoPermanente", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteResponse> TM_WS_RegistrarDireccionamientoPermanenteAsync(ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarProvisionesCobroEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueResponse TM_WS_ActualizarProvisionesCobroEmbarque(ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarProvisionesCobroEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueResponse> TM_WS_ActualizarProvisionesCobroEmbarqueAsync(ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarMemoEnviadoEmbarque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueResponse TM_WS_ActualizarMemoEnviadoEmbarque(ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarMemoEnviadoEmbarque", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueResponse> TM_WS_ActualizarMemoEnviadoEmbarqueAsync(ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarBLTrabajadoEnviado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoResponse TM_WS_ActualizarBLTrabajadoEnviado(ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ActualizarBLTrabajadoEnviado", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoResponse> TM_WS_ActualizarBLTrabajadoEnviadoAsync(ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ValidarRegistroEntidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.TM_WS_ValidarRegistroEntidadResponse TM_WS_ValidarRegistroEntidad(ServiceReference1.TM_WS_ValidarRegistroEntidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TM_WS_ValidarRegistroEntidad", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TM_WS_ValidarRegistroEntidadResponse> TM_WS_ValidarRegistroEntidadAsync(ServiceReference1.TM_WS_ValidarRegistroEntidadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ListarEmbarques", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ListarEmbarquesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short pAnio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short pTipoFiltro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pFiltro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pTipoEntidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pRuc_Entidad;
        
        public TM_WS_ListarEmbarquesRequest()
        {
        }
        
        public TM_WS_ListarEmbarquesRequest(string pEmpresa, short pAnio, short pTipoFiltro, string pFiltro, string pTipoEntidad, string pRuc_Entidad)
        {
            this.pEmpresa = pEmpresa;
            this.pAnio = pAnio;
            this.pTipoFiltro = pTipoFiltro;
            this.pFiltro = pFiltro;
            this.pTipoEntidad = pTipoEntidad;
            this.pRuc_Entidad = pRuc_Entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ListarEmbarquesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ListarEmbarquesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ListarEmbarquesResult;
        
        public TM_WS_ListarEmbarquesResponse()
        {
        }
        
        public TM_WS_ListarEmbarquesResponse(ServiceReference1.ArrayOfXElement TM_WS_ListarEmbarquesResult)
        {
            this.TM_WS_ListarEmbarquesResult = TM_WS_ListarEmbarquesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerInformacionEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerInformacionEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        public TM_WS_ObtenerInformacionEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerInformacionEmbarqueRequest(string pKeybld)
        {
            this.pKeybld = pKeybld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerInformacionEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerInformacionEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerInformacionEmbarqueResult;
        
        public TM_WS_ObtenerInformacionEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerInformacionEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerInformacionEmbarqueResult)
        {
            this.TM_WS_ObtenerInformacionEmbarqueResult = TM_WS_ObtenerInformacionEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerTrackingEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerTrackingEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        public TM_WS_ObtenerTrackingEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerTrackingEmbarqueRequest(string pKeybld)
        {
            this.pKeybld = pKeybld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerTrackingEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerTrackingEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerTrackingEmbarqueResult;
        
        public TM_WS_ObtenerTrackingEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerTrackingEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerTrackingEmbarqueResult)
        {
            this.TM_WS_ObtenerTrackingEmbarqueResult = TM_WS_ObtenerTrackingEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCobrosEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCobrosEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        public TM_WS_ObtenerCobrosEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerCobrosEmbarqueRequest(string pKeybld)
        {
            this.pKeybld = pKeybld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCobrosEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCobrosEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerCobrosEmbarqueResult;
        
        public TM_WS_ObtenerCobrosEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerCobrosEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerCobrosEmbarqueResult)
        {
            this.TM_WS_ObtenerCobrosEmbarqueResult = TM_WS_ObtenerCobrosEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pNrobl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public short pAnio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pUsuarioPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pTipDocumento;
        
        public TM_WS_RegistrarDocumentoRequest()
        {
        }
        
        public TM_WS_RegistrarDocumentoRequest(string pEmpresa, string pKeybld, string pNrobl, short pAnio, string pUsuarioPW, string pTipDocumento)
        {
            this.pEmpresa = pEmpresa;
            this.pKeybld = pKeybld;
            this.pNrobl = pNrobl;
            this.pAnio = pAnio;
            this.pUsuarioPW = pUsuarioPW;
            this.pTipDocumento = pTipDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_RegistrarDocumentoResult;
        
        public TM_WS_RegistrarDocumentoResponse()
        {
        }
        
        public TM_WS_RegistrarDocumentoResponse(ServiceReference1.ArrayOfXElement TM_WS_RegistrarDocumentoResult)
        {
            this.TM_WS_RegistrarDocumentoResult = TM_WS_RegistrarDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pArchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pMail;
        
        public TM_WS_ActualizarDocumentoRequest()
        {
        }
        
        public TM_WS_ActualizarDocumentoRequest(string pArchivo, string pMail)
        {
            this.pArchivo = pArchivo;
            this.pMail = pMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarDocumentoResult;
        
        public TM_WS_ActualizarDocumentoResponse()
        {
        }
        
        public TM_WS_ActualizarDocumentoResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarDocumentoResult)
        {
            this.TM_WS_ActualizarDocumentoResult = TM_WS_ActualizarDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarAgenteAduanasEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarAgenteAduanasEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short pOpcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pAgenteAduanasDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pAgenteAduanasDes;
        
        public TM_WS_ActualizarAgenteAduanasEmbarqueRequest()
        {
        }
        
        public TM_WS_ActualizarAgenteAduanasEmbarqueRequest(string pKeybld, short pOpcion, string pAgenteAduanasDoc, string pAgenteAduanasDes)
        {
            this.pKeybld = pKeybld;
            this.pOpcion = pOpcion;
            this.pAgenteAduanasDoc = pAgenteAduanasDoc;
            this.pAgenteAduanasDes = pAgenteAduanasDes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarAgenteAduanasEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarAgenteAduanasEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarAgenteAduanasEmbarqueResult;
        
        public TM_WS_ActualizarAgenteAduanasEmbarqueResponse()
        {
        }
        
        public TM_WS_ActualizarAgenteAduanasEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarAgenteAduanasEmbarqueResult)
        {
            this.TM_WS_ActualizarAgenteAduanasEmbarqueResult = TM_WS_ActualizarAgenteAduanasEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCobrosPendientesEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCobrosPendientesEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short pOpcion;
        
        public TM_WS_ObtenerCobrosPendientesEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerCobrosPendientesEmbarqueRequest(string pKeybld, short pOpcion)
        {
            this.pKeybld = pKeybld;
            this.pOpcion = pOpcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCobrosPendientesEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCobrosPendientesEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerCobrosPendientesEmbarqueResult;
        
        public TM_WS_ObtenerCobrosPendientesEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerCobrosPendientesEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerCobrosPendientesEmbarqueResult)
        {
            this.TM_WS_ObtenerCobrosPendientesEmbarqueResult = TM_WS_ObtenerCobrosPendientesEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerEntidades", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerEntidadesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pTipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pNumeroDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pRazonSocial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public short pOpcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short pTipoEntidad;
        
        public TM_WS_ObtenerEntidadesRequest()
        {
        }
        
        public TM_WS_ObtenerEntidadesRequest(string pTipoDocumento, string pNumeroDocumento, string pRazonSocial, short pOpcion, short pTipoEntidad)
        {
            this.pTipoDocumento = pTipoDocumento;
            this.pNumeroDocumento = pNumeroDocumento;
            this.pRazonSocial = pRazonSocial;
            this.pOpcion = pOpcion;
            this.pTipoEntidad = pTipoEntidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerEntidadesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerEntidadesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerEntidadesResult;
        
        public TM_WS_ObtenerEntidadesResponse()
        {
        }
        
        public TM_WS_ObtenerEntidadesResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerEntidadesResult)
        {
            this.TM_WS_ObtenerEntidadesResult = TM_WS_ObtenerEntidadesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerDesglosesEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerDesglosesEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short pOpcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short pAccion;
        
        public TM_WS_ObtenerDesglosesEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerDesglosesEmbarqueRequest(string pKeybld, short pOpcion, short pAccion)
        {
            this.pKeybld = pKeybld;
            this.pOpcion = pOpcion;
            this.pAccion = pAccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerDesglosesEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerDesglosesEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerDesglosesEmbarqueResult;
        
        public TM_WS_ObtenerDesglosesEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerDesglosesEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerDesglosesEmbarqueResult)
        {
            this.TM_WS_ObtenerDesglosesEmbarqueResult = TM_WS_ObtenerDesglosesEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarAutorizacionEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarAutorizacionEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        public TM_WS_ActualizarAutorizacionEmbarqueRequest()
        {
        }
        
        public TM_WS_ActualizarAutorizacionEmbarqueRequest(string pKeybld)
        {
            this.pKeybld = pKeybld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarAutorizacionEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarAutorizacionEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarAutorizacionEmbarqueResult;
        
        public TM_WS_ActualizarAutorizacionEmbarqueResponse()
        {
        }
        
        public TM_WS_ActualizarAutorizacionEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarAutorizacionEmbarqueResult)
        {
            this.TM_WS_ActualizarAutorizacionEmbarqueResult = TM_WS_ActualizarAutorizacionEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCreditoCobroEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCreditoCobroEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pTipoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pRucCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pFormaCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short pAccion;
        
        public TM_WS_ObtenerCreditoCobroEmbarqueRequest()
        {
        }
        
        public TM_WS_ObtenerCreditoCobroEmbarqueRequest(string pKeybld, string pTipoCliente, string pRucCliente, string pFormaCredito, short pAccion)
        {
            this.pKeybld = pKeybld;
            this.pTipoCliente = pTipoCliente;
            this.pRucCliente = pRucCliente;
            this.pFormaCredito = pFormaCredito;
            this.pAccion = pAccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerCreditoCobroEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerCreditoCobroEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerCreditoCobroEmbarqueResult;
        
        public TM_WS_ObtenerCreditoCobroEmbarqueResponse()
        {
        }
        
        public TM_WS_ObtenerCreditoCobroEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerCreditoCobroEmbarqueResult)
        {
            this.TM_WS_ObtenerCreditoCobroEmbarqueResult = TM_WS_ObtenerCreditoCobroEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudFacturacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudFacturacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pIdSolicitudPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pNroSolicitudPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pFechaSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pFechaEvaluacionSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pUsuarioPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string pTipoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string pRucCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string pTipoPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string pFormaPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string pId_Transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string pNumeroOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string pFecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public double pImporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string pUsuarioFinPW;
        
        public TM_WS_RegistrarSolicitudFacturacionRequest()
        {
        }
        
        public TM_WS_RegistrarSolicitudFacturacionRequest(
                    string pIdSolicitudPW, 
                    string pNroSolicitudPW, 
                    string pFechaSolicitud, 
                    string pFechaEvaluacionSolicitud, 
                    string pUsuarioPW, 
                    string pEmpresa, 
                    string pKeybld, 
                    string pTipoCliente, 
                    string pRucCliente, 
                    string pTipoPago, 
                    string pFormaPago, 
                    string pId_Transaccion, 
                    string pNumeroOperacion, 
                    string pFecha, 
                    double pImporte, 
                    string pUsuarioFinPW)
        {
            this.pIdSolicitudPW = pIdSolicitudPW;
            this.pNroSolicitudPW = pNroSolicitudPW;
            this.pFechaSolicitud = pFechaSolicitud;
            this.pFechaEvaluacionSolicitud = pFechaEvaluacionSolicitud;
            this.pUsuarioPW = pUsuarioPW;
            this.pEmpresa = pEmpresa;
            this.pKeybld = pKeybld;
            this.pTipoCliente = pTipoCliente;
            this.pRucCliente = pRucCliente;
            this.pTipoPago = pTipoPago;
            this.pFormaPago = pFormaPago;
            this.pId_Transaccion = pId_Transaccion;
            this.pNumeroOperacion = pNumeroOperacion;
            this.pFecha = pFecha;
            this.pImporte = pImporte;
            this.pUsuarioFinPW = pUsuarioFinPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudFacturacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudFacturacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudFacturacionResult;
        
        public TM_WS_RegistrarSolicitudFacturacionResponse()
        {
        }
        
        public TM_WS_RegistrarSolicitudFacturacionResponse(ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudFacturacionResult)
        {
            this.TM_WS_RegistrarSolicitudFacturacionResult = TM_WS_RegistrarSolicitudFacturacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudFacturacionDetalle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudFacturacionDetalleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pIdSolicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pRubroCCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pConcepCCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pMoneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double pImporte;
        
        public TM_WS_RegistrarSolicitudFacturacionDetalleRequest()
        {
        }
        
        public TM_WS_RegistrarSolicitudFacturacionDetalleRequest(string pIdSolicitud, string pRubroCCodigo, string pConcepCCodigo, string pMoneda, double pImporte)
        {
            this.pIdSolicitud = pIdSolicitud;
            this.pRubroCCodigo = pRubroCCodigo;
            this.pConcepCCodigo = pConcepCCodigo;
            this.pMoneda = pMoneda;
            this.pImporte = pImporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudFacturacionDetalleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudFacturacionDetalleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudFacturacionDetalleResult;
        
        public TM_WS_RegistrarSolicitudFacturacionDetalleResponse()
        {
        }
        
        public TM_WS_RegistrarSolicitudFacturacionDetalleResponse(ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudFacturacionDetalleResult)
        {
            this.TM_WS_RegistrarSolicitudFacturacionDetalleResult = TM_WS_RegistrarSolicitudFacturacionDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerEstadoSolicitudFacturacion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerEstadoSolicitudFacturacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pIdSolicitudPW;
        
        public TM_WS_ObtenerEstadoSolicitudFacturacionRequest()
        {
        }
        
        public TM_WS_ObtenerEstadoSolicitudFacturacionRequest(string pIdSolicitudPW)
        {
            this.pIdSolicitudPW = pIdSolicitudPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ObtenerEstadoSolicitudFacturacionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ObtenerEstadoSolicitudFacturacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ObtenerEstadoSolicitudFacturacionResult;
        
        public TM_WS_ObtenerEstadoSolicitudFacturacionResponse()
        {
        }
        
        public TM_WS_ObtenerEstadoSolicitudFacturacionResponse(ServiceReference1.ArrayOfXElement TM_WS_ObtenerEstadoSolicitudFacturacionResult)
        {
            this.TM_WS_ObtenerEstadoSolicitudFacturacionResult = TM_WS_ObtenerEstadoSolicitudFacturacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarPagosTercero", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarPagosTerceroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long pId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pCod_Tercero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pRUC_Tercero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pRSL_Tercero;
        
        public TM_WS_ActualizarPagosTerceroRequest()
        {
        }
        
        public TM_WS_ActualizarPagosTerceroRequest(string pKeybld, long pId, string pCod_Tercero, string pRUC_Tercero, string pRSL_Tercero)
        {
            this.pKeybld = pKeybld;
            this.pId = pId;
            this.pCod_Tercero = pCod_Tercero;
            this.pRUC_Tercero = pRUC_Tercero;
            this.pRSL_Tercero = pRSL_Tercero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarPagosTerceroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarPagosTerceroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarPagosTerceroResult;
        
        public TM_WS_ActualizarPagosTerceroResponse()
        {
        }
        
        public TM_WS_ActualizarPagosTerceroResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarPagosTerceroResult)
        {
            this.TM_WS_ActualizarPagosTerceroResult = TM_WS_ActualizarPagosTerceroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudDireccionamiento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudDireccionamientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pIdSolicitudPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pNroSolicitudPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pModalidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pDeposito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string pEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string pUsuarioPW;
        
        public TM_WS_RegistrarSolicitudDireccionamientoRequest()
        {
        }
        
        public TM_WS_RegistrarSolicitudDireccionamientoRequest(string pIdSolicitudPW, string pNroSolicitudPW, string pEmpresa, string pKeybld, string pModalidad, string pDeposito, string pEstado, string pUsuarioPW)
        {
            this.pIdSolicitudPW = pIdSolicitudPW;
            this.pNroSolicitudPW = pNroSolicitudPW;
            this.pEmpresa = pEmpresa;
            this.pKeybld = pKeybld;
            this.pModalidad = pModalidad;
            this.pDeposito = pDeposito;
            this.pEstado = pEstado;
            this.pUsuarioPW = pUsuarioPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarSolicitudDireccionamientoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarSolicitudDireccionamientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudDireccionamientoResult;
        
        public TM_WS_RegistrarSolicitudDireccionamientoResponse()
        {
        }
        
        public TM_WS_RegistrarSolicitudDireccionamientoResponse(ServiceReference1.ArrayOfXElement TM_WS_RegistrarSolicitudDireccionamientoResult)
        {
            this.TM_WS_RegistrarSolicitudDireccionamientoResult = TM_WS_RegistrarSolicitudDireccionamientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarEstadoSolicitudDireccionamiento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pIdSolicitudPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pUsuarioPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pMotivo;
        
        public TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest()
        {
        }
        
        public TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest(string pIdSolicitudPW, string pUsuarioPW, string pEstado, string pMotivo)
        {
            this.pIdSolicitudPW = pIdSolicitudPW;
            this.pUsuarioPW = pUsuarioPW;
            this.pEstado = pEstado;
            this.pMotivo = pMotivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarEstadoSolicitudDireccionamientoResult;
        
        public TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse()
        {
        }
        
        public TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarEstadoSolicitudDireccionamientoResult)
        {
            this.TM_WS_ActualizarEstadoSolicitudDireccionamientoResult = TM_WS_ActualizarEstadoSolicitudDireccionamientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarDireccionamientoPermanente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarDireccionamientoPermanenteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pDeposito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pUsuarioPW;
        
        public TM_WS_RegistrarDireccionamientoPermanenteRequest()
        {
        }
        
        public TM_WS_RegistrarDireccionamientoPermanenteRequest(string pEmpresa, string pKeybld, string pDeposito, string pUsuarioPW)
        {
            this.pEmpresa = pEmpresa;
            this.pKeybld = pKeybld;
            this.pDeposito = pDeposito;
            this.pUsuarioPW = pUsuarioPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_RegistrarDireccionamientoPermanenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_RegistrarDireccionamientoPermanenteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_RegistrarDireccionamientoPermanenteResult;
        
        public TM_WS_RegistrarDireccionamientoPermanenteResponse()
        {
        }
        
        public TM_WS_RegistrarDireccionamientoPermanenteResponse(ServiceReference1.ArrayOfXElement TM_WS_RegistrarDireccionamientoPermanenteResult)
        {
            this.TM_WS_RegistrarDireccionamientoPermanenteResult = TM_WS_RegistrarDireccionamientoPermanenteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarProvisionesCobroEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarProvisionesCobroEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long pId;
        
        public TM_WS_ActualizarProvisionesCobroEmbarqueRequest()
        {
        }
        
        public TM_WS_ActualizarProvisionesCobroEmbarqueRequest(string pKeybld, long pId)
        {
            this.pKeybld = pKeybld;
            this.pId = pId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarProvisionesCobroEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarProvisionesCobroEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarProvisionesCobroEmbarqueResult;
        
        public TM_WS_ActualizarProvisionesCobroEmbarqueResponse()
        {
        }
        
        public TM_WS_ActualizarProvisionesCobroEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarProvisionesCobroEmbarqueResult)
        {
            this.TM_WS_ActualizarProvisionesCobroEmbarqueResult = TM_WS_ActualizarProvisionesCobroEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarMemoEnviadoEmbarque", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarMemoEnviadoEmbarqueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pNomArchivo;
        
        public TM_WS_ActualizarMemoEnviadoEmbarqueRequest()
        {
        }
        
        public TM_WS_ActualizarMemoEnviadoEmbarqueRequest(string pKeybld, string pNomArchivo)
        {
            this.pKeybld = pKeybld;
            this.pNomArchivo = pNomArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarMemoEnviadoEmbarqueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarMemoEnviadoEmbarqueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarMemoEnviadoEmbarqueResult;
        
        public TM_WS_ActualizarMemoEnviadoEmbarqueResponse()
        {
        }
        
        public TM_WS_ActualizarMemoEnviadoEmbarqueResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarMemoEnviadoEmbarqueResult)
        {
            this.TM_WS_ActualizarMemoEnviadoEmbarqueResult = TM_WS_ActualizarMemoEnviadoEmbarqueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarBLTrabajadoEnviado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarBLTrabajadoEnviadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pKeybld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pNomArchivo;
        
        public TM_WS_ActualizarBLTrabajadoEnviadoRequest()
        {
        }
        
        public TM_WS_ActualizarBLTrabajadoEnviadoRequest(string pKeybld, string pNomArchivo)
        {
            this.pKeybld = pKeybld;
            this.pNomArchivo = pNomArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ActualizarBLTrabajadoEnviadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ActualizarBLTrabajadoEnviadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ActualizarBLTrabajadoEnviadoResult;
        
        public TM_WS_ActualizarBLTrabajadoEnviadoResponse()
        {
        }
        
        public TM_WS_ActualizarBLTrabajadoEnviadoResponse(ServiceReference1.ArrayOfXElement TM_WS_ActualizarBLTrabajadoEnviadoResult)
        {
            this.TM_WS_ActualizarBLTrabajadoEnviadoResult = TM_WS_ActualizarBLTrabajadoEnviadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ValidarRegistroEntidad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ValidarRegistroEntidadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string pTipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pMail;
        
        public TM_WS_ValidarRegistroEntidadRequest()
        {
        }
        
        public TM_WS_ValidarRegistroEntidadRequest(string pTipo, string pRuc, string pMail)
        {
            this.pTipo = pTipo;
            this.pRuc = pRuc;
            this.pMail = pMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TM_WS_ValidarRegistroEntidadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TM_WS_ValidarRegistroEntidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ArrayOfXElement TM_WS_ValidarRegistroEntidadResult;
        
        public TM_WS_ValidarRegistroEntidadResponse()
        {
        }
        
        public TM_WS_ValidarRegistroEntidadResponse(ServiceReference1.ArrayOfXElement TM_WS_ValidarRegistroEntidadResult)
        {
            this.TM_WS_ValidarRegistroEntidadResult = TM_WS_ValidarRegistroEntidadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService_TM_PWSoapChannel : ServiceReference1.WebService_TM_PWSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService_TM_PWSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebService_TM_PWSoap>, ServiceReference1.WebService_TM_PWSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService_TM_PWSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService_TM_PWSoapClient.GetBindingForEndpoint(endpointConfiguration), WebService_TM_PWSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService_TM_PWSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService_TM_PWSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService_TM_PWSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService_TM_PWSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService_TM_PWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.TM_WS_ListarEmbarquesResponse TM_WS_ListarEmbarques(ServiceReference1.TM_WS_ListarEmbarquesRequest request)
        {
            return base.Channel.TM_WS_ListarEmbarques(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ListarEmbarquesResponse> TM_WS_ListarEmbarquesAsync(ServiceReference1.TM_WS_ListarEmbarquesRequest request)
        {
            return base.Channel.TM_WS_ListarEmbarquesAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerInformacionEmbarqueResponse TM_WS_ObtenerInformacionEmbarque(ServiceReference1.TM_WS_ObtenerInformacionEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerInformacionEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerInformacionEmbarqueResponse> TM_WS_ObtenerInformacionEmbarqueAsync(ServiceReference1.TM_WS_ObtenerInformacionEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerInformacionEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerTrackingEmbarqueResponse TM_WS_ObtenerTrackingEmbarque(ServiceReference1.TM_WS_ObtenerTrackingEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerTrackingEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerTrackingEmbarqueResponse> TM_WS_ObtenerTrackingEmbarqueAsync(ServiceReference1.TM_WS_ObtenerTrackingEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerTrackingEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerCobrosEmbarqueResponse TM_WS_ObtenerCobrosEmbarque(ServiceReference1.TM_WS_ObtenerCobrosEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCobrosEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCobrosEmbarqueResponse> TM_WS_ObtenerCobrosEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCobrosEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCobrosEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_RegistrarDocumentoResponse TM_WS_RegistrarDocumento(ServiceReference1.TM_WS_RegistrarDocumentoRequest request)
        {
            return base.Channel.TM_WS_RegistrarDocumento(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarDocumentoResponse> TM_WS_RegistrarDocumentoAsync(ServiceReference1.TM_WS_RegistrarDocumentoRequest request)
        {
            return base.Channel.TM_WS_RegistrarDocumentoAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarDocumentoResponse TM_WS_ActualizarDocumento(ServiceReference1.TM_WS_ActualizarDocumentoRequest request)
        {
            return base.Channel.TM_WS_ActualizarDocumento(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarDocumentoResponse> TM_WS_ActualizarDocumentoAsync(ServiceReference1.TM_WS_ActualizarDocumentoRequest request)
        {
            return base.Channel.TM_WS_ActualizarDocumentoAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueResponse TM_WS_ActualizarAgenteAduanasEmbarque(ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarAgenteAduanasEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueResponse> TM_WS_ActualizarAgenteAduanasEmbarqueAsync(ServiceReference1.TM_WS_ActualizarAgenteAduanasEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarAgenteAduanasEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueResponse TM_WS_ObtenerCobrosPendientesEmbarque(ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCobrosPendientesEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueResponse> TM_WS_ObtenerCobrosPendientesEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCobrosPendientesEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCobrosPendientesEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerEntidadesResponse TM_WS_ObtenerEntidades(ServiceReference1.TM_WS_ObtenerEntidadesRequest request)
        {
            return base.Channel.TM_WS_ObtenerEntidades(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerEntidadesResponse> TM_WS_ObtenerEntidadesAsync(ServiceReference1.TM_WS_ObtenerEntidadesRequest request)
        {
            return base.Channel.TM_WS_ObtenerEntidadesAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueResponse TM_WS_ObtenerDesglosesEmbarque(ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerDesglosesEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueResponse> TM_WS_ObtenerDesglosesEmbarqueAsync(ServiceReference1.TM_WS_ObtenerDesglosesEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerDesglosesEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueResponse TM_WS_ActualizarAutorizacionEmbarque(ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarAutorizacionEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueResponse> TM_WS_ActualizarAutorizacionEmbarqueAsync(ServiceReference1.TM_WS_ActualizarAutorizacionEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarAutorizacionEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueResponse TM_WS_ObtenerCreditoCobroEmbarque(ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCreditoCobroEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueResponse> TM_WS_ObtenerCreditoCobroEmbarqueAsync(ServiceReference1.TM_WS_ObtenerCreditoCobroEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ObtenerCreditoCobroEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_RegistrarSolicitudFacturacionResponse TM_WS_RegistrarSolicitudFacturacion(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudFacturacion(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudFacturacionResponse> TM_WS_RegistrarSolicitudFacturacionAsync(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudFacturacionAsync(request);
        }
        
        public ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleResponse TM_WS_RegistrarSolicitudFacturacionDetalle(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudFacturacionDetalle(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleResponse> TM_WS_RegistrarSolicitudFacturacionDetalleAsync(ServiceReference1.TM_WS_RegistrarSolicitudFacturacionDetalleRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudFacturacionDetalleAsync(request);
        }
        
        public ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionResponse TM_WS_ObtenerEstadoSolicitudFacturacion(ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionRequest request)
        {
            return base.Channel.TM_WS_ObtenerEstadoSolicitudFacturacion(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionResponse> TM_WS_ObtenerEstadoSolicitudFacturacionAsync(ServiceReference1.TM_WS_ObtenerEstadoSolicitudFacturacionRequest request)
        {
            return base.Channel.TM_WS_ObtenerEstadoSolicitudFacturacionAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarPagosTerceroResponse TM_WS_ActualizarPagosTercero(ServiceReference1.TM_WS_ActualizarPagosTerceroRequest request)
        {
            return base.Channel.TM_WS_ActualizarPagosTercero(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarPagosTerceroResponse> TM_WS_ActualizarPagosTerceroAsync(ServiceReference1.TM_WS_ActualizarPagosTerceroRequest request)
        {
            return base.Channel.TM_WS_ActualizarPagosTerceroAsync(request);
        }
        
        public ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoResponse TM_WS_RegistrarSolicitudDireccionamiento(ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudDireccionamiento(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoResponse> TM_WS_RegistrarSolicitudDireccionamientoAsync(ServiceReference1.TM_WS_RegistrarSolicitudDireccionamientoRequest request)
        {
            return base.Channel.TM_WS_RegistrarSolicitudDireccionamientoAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse TM_WS_ActualizarEstadoSolicitudDireccionamiento(ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest request)
        {
            return base.Channel.TM_WS_ActualizarEstadoSolicitudDireccionamiento(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoResponse> TM_WS_ActualizarEstadoSolicitudDireccionamientoAsync(ServiceReference1.TM_WS_ActualizarEstadoSolicitudDireccionamientoRequest request)
        {
            return base.Channel.TM_WS_ActualizarEstadoSolicitudDireccionamientoAsync(request);
        }
        
        public ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteResponse TM_WS_RegistrarDireccionamientoPermanente(ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteRequest request)
        {
            return base.Channel.TM_WS_RegistrarDireccionamientoPermanente(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteResponse> TM_WS_RegistrarDireccionamientoPermanenteAsync(ServiceReference1.TM_WS_RegistrarDireccionamientoPermanenteRequest request)
        {
            return base.Channel.TM_WS_RegistrarDireccionamientoPermanenteAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueResponse TM_WS_ActualizarProvisionesCobroEmbarque(ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarProvisionesCobroEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueResponse> TM_WS_ActualizarProvisionesCobroEmbarqueAsync(ServiceReference1.TM_WS_ActualizarProvisionesCobroEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarProvisionesCobroEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueResponse TM_WS_ActualizarMemoEnviadoEmbarque(ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarMemoEnviadoEmbarque(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueResponse> TM_WS_ActualizarMemoEnviadoEmbarqueAsync(ServiceReference1.TM_WS_ActualizarMemoEnviadoEmbarqueRequest request)
        {
            return base.Channel.TM_WS_ActualizarMemoEnviadoEmbarqueAsync(request);
        }
        
        public ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoResponse TM_WS_ActualizarBLTrabajadoEnviado(ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoRequest request)
        {
            return base.Channel.TM_WS_ActualizarBLTrabajadoEnviado(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoResponse> TM_WS_ActualizarBLTrabajadoEnviadoAsync(ServiceReference1.TM_WS_ActualizarBLTrabajadoEnviadoRequest request)
        {
            return base.Channel.TM_WS_ActualizarBLTrabajadoEnviadoAsync(request);
        }
        
        public ServiceReference1.TM_WS_ValidarRegistroEntidadResponse TM_WS_ValidarRegistroEntidad(ServiceReference1.TM_WS_ValidarRegistroEntidadRequest request)
        {
            return base.Channel.TM_WS_ValidarRegistroEntidad(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TM_WS_ValidarRegistroEntidadResponse> TM_WS_ValidarRegistroEntidadAsync(ServiceReference1.TM_WS_ValidarRegistroEntidadRequest request)
        {
            return base.Channel.TM_WS_ValidarRegistroEntidadAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService_TM_PWSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService_TM_PWSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService_TM_PWSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://200.62.226.235:8092/webservice_TM_PW.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService_TM_PWSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://200.62.226.235:8092/webservice_TM_PW.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService_TM_PWSoap,
            
            WebService_TM_PWSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
